name: CTRL-V Life Public Metrics
on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  ithub-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Organization introduction
        uses: lowlighter/metrics@latest
        with:
          user: CTRL-V-Life
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.introduction.svg
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes