name: Norfair00 Profile metrics
on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Organization introduction
        uses: lowlighter/metrics@latest
        with:
          config_timezone: Europe/Paris
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: CTRL-V-Life
          base: header
          plugin_introduction: yes